# Generated by Django 6.0 on 2026-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('indicator', models.CharField(max_length=255)),
                ('gender', models.CharField(default='Total', max_length=20)),
                ('value', models.FloatField()),
            ],
        ),
    ]
